services:
  sms_client:
    build: ./client
    image: mhallihamza/sms_client
    container_name: sms_client
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      - api-gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./server/apps/api-gateway/Dockerfile
    image: mhallihamza/sms_api-gateway
    container_name: api-gateway
    ports:
      - '3000:3000'
    networks:
      - app-network
  
  auth:
    build:
      context: .
      dockerfile: ./server/apps/auth/Dockerfile
    image: mhallihamza/sms_auth
    container_name: auth
    ports:
      - '3001:3001'
    networks:
      - app-network
    
  users:
    build:
      context: .
      dockerfile: ./server/apps/users/Dockerfile
    image: mhallihamza/sms_users
    container_name: users
    ports:
      - '3002:3002'
    networks:
      - app-network  

  customers:
    build:
      context: .
      dockerfile: ./server/apps/customers/Dockerfile
    image: mhallihamza/sms_customers
    container_name: customers
    ports:
      - '3003:3003'
    networks:
      - app-network
    
  appointments:
    build:
      context: .
      dockerfile: ./server/apps/appointments/Dockerfile
    image: mhallihamza/sms_appointments
    container_name: appointments
    ports:
      - '3004:3004'
    networks:
      - app-network
    
  staff:
    build:
      context: .
      dockerfile: ./server/apps/staff/Dockerfile
    image: mhallihamza/sms_staff
    container_name: staff
    ports:
      - '3005:3005'
    networks:
      - app-network
    
  services:
    build:
      context: .
      dockerfile: ./server/apps/services/Dockerfile
    image: mhallihamza/sms_services
    container_name: services
    ports:
      - '3006:3006'
    networks:
      - app-network
  
  treatments:
    build:
      context: .
      dockerfile: ./server/apps/treatments/Dockerfile
    image: mhallihamza/sms_treatments
    container_name: treatments
    ports:
      - '3007:3007'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
      